'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {
  ANALYTICS: '__GATHER_ANALYTICS',
  CREATE_SESSION: '__GATHER_CREATE_SESSION',
  GET_SESSION: '__GATHER_GET_SESSION',
  MODIFY_ME: '__GATHER_MODIFY_ME',
  DELETE_SESSION: '__GATHER_DELETE_SESSION',
  CREATE_ME_DEVICE: '__GATHER_CREATE_ME_DEVICE',
  FETCH_NOTIFICATIONS: '__GATHER_FETCH_NOTIFICATIONS',
  REQUEST_INVITE: '__GATHER_REQUEST_INVITE'
};